version: '3.9'

services:
  pgvector-db:
    image: ankane/pgvector
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    ports:
      - "8501:8501"
    depends_on:
      pgvector-db:
        condition: service_healthy
    environment:
      POSTGRES_DB_NAME: mydb
      POSTGRES_DB_USER: postgres
      POSTGRES_DB_PASSWORD: postgres
      POSTGRES_DB_HOST: pgvector-db
      POSTGRES_DB_PORT: 5432
      OPENAI_API_KEY: your-openai-key-here
    volumes:
      - .:/app

volumes:
  pgdata:
